<?php

$dir = dirname(__DIR__).'/data/cms';

$modifiers = [
    ['code' => '22', 'description' => 'Increased Procedural Services', 'level' => 'cpt'],
    ['code' => '23', 'description' => 'Unusual Anesthesia', 'level' => 'cpt'],
    ['code' => '24', 'description' => 'Unrelated E/M Service During Postoperative Period', 'level' => 'cpt'],
    ['code' => '25', 'description' => 'Significant, Separately Identifiable E/M Service', 'level' => 'cpt'],
    ['code' => '26', 'description' => 'Professional Component', 'level' => 'cpt'],
    ['code' => '27', 'description' => 'Multiple Outpatient Hospital E/M Encounters Same Date', 'level' => 'cpt'],
    ['code' => '32', 'description' => 'Mandated Services', 'level' => 'cpt'],
    ['code' => '33', 'description' => 'Preventive Services', 'level' => 'cpt'],
    ['code' => '47', 'description' => 'Anesthesia by Surgeon', 'level' => 'cpt'],
    ['code' => '50', 'description' => 'Bilateral Procedure', 'level' => 'cpt'],
    ['code' => '51', 'description' => 'Multiple Procedures', 'level' => 'cpt'],
    ['code' => '52', 'description' => 'Reduced Services', 'level' => 'cpt'],
    ['code' => '53', 'description' => 'Discontinued Procedure', 'level' => 'cpt'],
    ['code' => '54', 'description' => 'Surgical Care Only', 'level' => 'cpt'],
    ['code' => '55', 'description' => 'Postoperative Management Only', 'level' => 'cpt'],
    ['code' => '56', 'description' => 'Preoperative Management Only', 'level' => 'cpt'],
    ['code' => '57', 'description' => 'Decision for Surgery', 'level' => 'cpt'],
    ['code' => '58', 'description' => 'Staged or Related Procedure During Postoperative Period', 'level' => 'cpt'],
    ['code' => '59', 'description' => 'Distinct Procedural Service', 'level' => 'cpt'],
    ['code' => '62', 'description' => 'Two Surgeons', 'level' => 'cpt'],
    ['code' => '63', 'description' => 'Procedure Performed on Infants', 'level' => 'cpt'],
    ['code' => '66', 'description' => 'Surgical Team', 'level' => 'cpt'],
    ['code' => '73', 'description' => 'Discontinued Outpatient Procedure Prior to Anesthesia', 'level' => 'cpt'],
    ['code' => '74', 'description' => 'Discontinued Outpatient Procedure After Anesthesia', 'level' => 'cpt'],
    ['code' => '76', 'description' => 'Repeat Procedure by Same Physician', 'level' => 'cpt'],
    ['code' => '77', 'description' => 'Repeat Procedure by Another Physician', 'level' => 'cpt'],
    ['code' => '78', 'description' => 'Unplanned Return to Operating Room', 'level' => 'cpt'],
    ['code' => '79', 'description' => 'Unrelated Procedure During Postoperative Period', 'level' => 'cpt'],
    ['code' => '80', 'description' => 'Assistant Surgeon', 'level' => 'cpt'],
    ['code' => '81', 'description' => 'Minimum Assistant Surgeon', 'level' => 'cpt'],
    ['code' => '82', 'description' => 'Assistant Surgeon (qualified resident not available)', 'level' => 'cpt'],
    ['code' => '90', 'description' => 'Reference (Outside) Laboratory', 'level' => 'cpt'],
    ['code' => '91', 'description' => 'Repeat Clinical Diagnostic Laboratory Test', 'level' => 'cpt'],
    ['code' => '92', 'description' => 'Alternative Laboratory Platform Testing', 'level' => 'cpt'],
    ['code' => '95', 'description' => 'Synchronous Telemedicine via Real-Time Audio and Video', 'level' => 'cpt'],
    ['code' => '96', 'description' => 'Habilitative Services', 'level' => 'cpt'],
    ['code' => '97', 'description' => 'Rehabilitative Services', 'level' => 'cpt'],
    ['code' => '99', 'description' => 'Multiple Modifiers', 'level' => 'cpt'],
    ['code' => 'TC', 'description' => 'Technical Component', 'level' => 'cpt'],
    ['code' => 'XE', 'description' => 'Separate Encounter', 'level' => 'cpt'],
    ['code' => 'XP', 'description' => 'Separate Practitioner', 'level' => 'cpt'],
    ['code' => 'XS', 'description' => 'Separate Structure', 'level' => 'cpt'],
    ['code' => 'XU', 'description' => 'Unusual Non-Overlapping Service', 'level' => 'cpt'],
    ['code' => 'LT', 'description' => 'Left Side', 'level' => 'hcpcs'],
    ['code' => 'RT', 'description' => 'Right Side', 'level' => 'hcpcs'],
    ['code' => 'GA', 'description' => 'Waiver of Liability Statement Issued as Required by Payer Policy', 'level' => 'hcpcs'],
    ['code' => 'GC', 'description' => 'Service Performed in Part by Resident Under Teaching Physician', 'level' => 'hcpcs'],
    ['code' => 'GE', 'description' => 'Service Performed by Resident Without Teaching Physician Present', 'level' => 'hcpcs'],
    ['code' => 'GF', 'description' => 'Non-physician Service in Critical Access or Rural Health Clinic', 'level' => 'hcpcs'],
    ['code' => 'GN', 'description' => 'Services Under Outpatient Speech Language Pathology Plan of Care', 'level' => 'hcpcs'],
    ['code' => 'GO', 'description' => 'Services Under Outpatient Occupational Therapy Plan of Care', 'level' => 'hcpcs'],
    ['code' => 'GP', 'description' => 'Services Under Outpatient Physical Therapy Plan of Care', 'level' => 'hcpcs'],
    ['code' => 'GT', 'description' => 'Via Interactive Audio and Video Telecommunications Systems', 'level' => 'hcpcs'],
    ['code' => 'GV', 'description' => 'Attending Physician Not Employed or Paid Under Arrangement by Hospital', 'level' => 'hcpcs'],
    ['code' => 'GW', 'description' => 'Service Not Related to Hospice Patient Terminal Condition', 'level' => 'hcpcs'],
    ['code' => 'GY', 'description' => 'Item or Service Statutorily Excluded', 'level' => 'hcpcs'],
    ['code' => 'GZ', 'description' => 'Item or Service Expected to be Denied as Not Reasonable and Necessary', 'level' => 'hcpcs'],
    ['code' => 'AQ', 'description' => 'Physician Service in Health Professional Shortage Area', 'level' => 'hcpcs'],
    ['code' => 'AS', 'description' => 'PA, NP, or Clinical Nurse Specialist Services for Assistant at Surgery', 'level' => 'hcpcs'],
];

$carc = [
    ['code' => '1', 'group_code' => 'CO', 'description' => 'Deductible Amount'],
    ['code' => '2', 'group_code' => 'CO', 'description' => 'Coinsurance Amount'],
    ['code' => '3', 'group_code' => 'CO', 'description' => 'Co-payment Amount'],
    ['code' => '4', 'group_code' => 'OA', 'description' => 'The procedure code is inconsistent with the modifier used or a required modifier is missing'],
    ['code' => '5', 'group_code' => 'CO', 'description' => 'The procedure code/type of bill is inconsistent with the place of service'],
    ['code' => '6', 'group_code' => 'CO', 'description' => 'The procedure/revenue code is inconsistent with the patient\'s age'],
    ['code' => '7', 'group_code' => 'CO', 'description' => 'The procedure/revenue code is inconsistent with the patient\'s gender'],
    ['code' => '8', 'group_code' => 'CO', 'description' => 'The procedure code is inconsistent with the provider type/specialty'],
    ['code' => '9', 'group_code' => 'CO', 'description' => 'The diagnosis is inconsistent with the patient\'s age'],
    ['code' => '10', 'group_code' => 'CO', 'description' => 'The diagnosis is inconsistent with the patient\'s gender'],
    ['code' => '11', 'group_code' => 'CO', 'description' => 'The diagnosis is inconsistent with the procedure'],
    ['code' => '12', 'group_code' => 'CO', 'description' => 'The diagnosis is inconsistent with the provider type'],
    ['code' => '13', 'group_code' => 'CO', 'description' => 'The date of death precedes the date of service'],
    ['code' => '14', 'group_code' => 'CO', 'description' => 'The date of birth follows the date of service'],
    ['code' => '15', 'group_code' => 'CO', 'description' => 'The authorization number is missing, invalid, or does not apply'],
    ['code' => '16', 'group_code' => 'CO', 'description' => 'Claim/service lacks information or has submission/billing error(s)'],
    ['code' => '18', 'group_code' => 'CO', 'description' => 'Duplicate claim/service'],
    ['code' => '22', 'group_code' => 'CO', 'description' => 'This care may be covered by another payer per coordination of benefits'],
    ['code' => '23', 'group_code' => 'CO', 'description' => 'The impact of prior payer(s) adjudication including payments and/or adjustments'],
    ['code' => '24', 'group_code' => 'CO', 'description' => 'Charges are covered under a capitation agreement/managed care plan'],
    ['code' => '26', 'group_code' => 'CO', 'description' => 'Expenses incurred prior to coverage'],
    ['code' => '27', 'group_code' => 'CO', 'description' => 'Expenses incurred after coverage terminated'],
    ['code' => '29', 'group_code' => 'CO', 'description' => 'The time limit for filing has expired'],
    ['code' => '31', 'group_code' => 'CO', 'description' => 'Patient cannot be identified as our insured'],
    ['code' => '32', 'group_code' => 'CO', 'description' => 'Our records indicate that this dependent is not an eligible dependent as defined'],
    ['code' => '33', 'group_code' => 'CO', 'description' => 'Insured has no dependent coverage'],
    ['code' => '34', 'group_code' => 'CO', 'description' => 'Insured has no coverage for newborns'],
    ['code' => '35', 'group_code' => 'CO', 'description' => 'Lifetime benefit maximum has been reached'],
    ['code' => '39', 'group_code' => 'CO', 'description' => 'Services denied at the time authorization/pre-certification was requested'],
    ['code' => '40', 'group_code' => 'CO', 'description' => 'Charges do not meet qualifications for emergent/urgent care'],
    ['code' => '45', 'group_code' => 'CO', 'description' => 'Charge exceeds fee schedule/maximum allowable or contracted/legislated fee arrangement'],
    ['code' => '49', 'group_code' => 'CO', 'description' => 'This is a non-covered service because it is a routine/preventive exam or a diagnostic/screening procedure'],
    ['code' => '50', 'group_code' => 'CO', 'description' => 'These are non-covered services because this is not deemed a medical necessity'],
    ['code' => '51', 'group_code' => 'CO', 'description' => 'These are non-covered services because this is a pre-existing condition'],
    ['code' => '53', 'group_code' => 'CO', 'description' => 'Services by an immediate relative or a member of the same household are not covered'],
    ['code' => '54', 'group_code' => 'CO', 'description' => 'Multiple physicians/assistants are not covered in this case'],
    ['code' => '55', 'group_code' => 'CO', 'description' => 'Procedure/treatment/drug is deemed experimental/investigational by the payer'],
    ['code' => '56', 'group_code' => 'CO', 'description' => 'Procedure/treatment has not been deemed proven to be effective by the payer'],
    ['code' => '58', 'group_code' => 'CO', 'description' => 'Treatment was deemed by the payer to have been rendered in an inappropriate or invalid place of service'],
    ['code' => '59', 'group_code' => 'CO', 'description' => 'Processed based on multiple or concurrent procedure rules'],
    ['code' => '60', 'group_code' => 'CO', 'description' => 'Charges for outpatient services are not covered when performed within a period prior to or after inpatient stay'],
    ['code' => '66', 'group_code' => 'CO', 'description' => 'Blood Deductible'],
    ['code' => '89', 'group_code' => 'CO', 'description' => 'Professional fees removed from charges because included in facility payment'],
    ['code' => '90', 'group_code' => 'CO', 'description' => 'Ingredient cost adjustment'],
    ['code' => '91', 'group_code' => 'CO', 'description' => 'Dispensing fee adjustment'],
    ['code' => '94', 'group_code' => 'CO', 'description' => 'Processed in Excess of charges'],
    ['code' => '96', 'group_code' => 'CO', 'description' => 'Non-covered charge(s)'],
    ['code' => '97', 'group_code' => 'CO', 'description' => 'The benefit for this service is included in the payment/allowance for another service/procedure'],
    ['code' => '100', 'group_code' => 'PI', 'description' => 'Payment made to patient/insured/responsible party/employer'],
    ['code' => '101', 'group_code' => 'PI', 'description' => 'Predetermination: anticipated payment upon completion of services or claim adjudication'],
    ['code' => '102', 'group_code' => 'PI', 'description' => 'Major Medical Adjustment'],
    ['code' => '103', 'group_code' => 'PI', 'description' => 'Provider promotional discount'],
    ['code' => '104', 'group_code' => 'PI', 'description' => 'Managed care withholding'],
    ['code' => '105', 'group_code' => 'PI', 'description' => 'Tax withholding'],
    ['code' => '109', 'group_code' => 'CO', 'description' => 'Claim not covered by this payer/contractor. You must send the claim to the correct payer/contractor'],
    ['code' => '110', 'group_code' => 'CO', 'description' => 'Billing date predates service date'],
    ['code' => '111', 'group_code' => 'CO', 'description' => 'Not covered unless the provider accepts assignment'],
    ['code' => '112', 'group_code' => 'CO', 'description' => 'Service not furnished directly to the patient and/or not documented'],
    ['code' => '114', 'group_code' => 'CO', 'description' => 'Procedure/product not approved by the Food and Drug Administration'],
    ['code' => '119', 'group_code' => 'CO', 'description' => 'Benefit maximum for this time period or occurrence has been reached'],
    ['code' => '121', 'group_code' => 'CO', 'description' => 'Indemnification adjustment - compensation for outstanding member responsibility'],
    ['code' => '125', 'group_code' => 'CO', 'description' => 'Submission/billing error(s). At least one Remark Code must be provided'],
    ['code' => '128', 'group_code' => 'CO', 'description' => 'Newborn\'s services are covered in the mother\'s Allowance'],
    ['code' => '129', 'group_code' => 'CO', 'description' => 'Prior processing information appears incorrect. If you disagree, contact payer'],
    ['code' => '130', 'group_code' => 'CO', 'description' => 'Claim submission fee'],
    ['code' => '131', 'group_code' => 'CO', 'description' => 'Claim specific negotiated discount'],
    ['code' => '132', 'group_code' => 'CO', 'description' => 'Prearranged demonstration project adjustment'],
    ['code' => '133', 'group_code' => 'CO', 'description' => 'The disposition of this claim/service is pending further review'],
    ['code' => '134', 'group_code' => 'CO', 'description' => 'Technical fees removed from charges'],
    ['code' => '135', 'group_code' => 'CO', 'description' => 'Interim bills cannot be processed'],
    ['code' => '136', 'group_code' => 'CO', 'description' => 'Failure to follow prior payer\'s coverage rules'],
    ['code' => '137', 'group_code' => 'CO', 'description' => 'Regulatory Surcharges, Assessments, Allowances or Health Related Taxes'],
    ['code' => '139', 'group_code' => 'CO', 'description' => 'Contracted funding agreement - Subscriber is employed by the provider of services'],
    ['code' => '140', 'group_code' => 'CO', 'description' => 'Patient/Insured health identification number and name do not match'],
    ['code' => '142', 'group_code' => 'CO', 'description' => 'Monthly Medicaid patient liability amount'],
    ['code' => '143', 'group_code' => 'CO', 'description' => 'Portion of payment deferred'],
    ['code' => '144', 'group_code' => 'CO', 'description' => 'Incentive adjustment, e.g. preferred product/service'],
    ['code' => '146', 'group_code' => 'CO', 'description' => 'Diagnosis was invalid for the date(s) of service reported'],
    ['code' => '147', 'group_code' => 'CO', 'description' => 'Provider contracted/negotiated rate expired or not on file'],
    ['code' => '148', 'group_code' => 'CO', 'description' => 'Information from another provider was not provided or was insufficient/incomplete'],
    ['code' => '149', 'group_code' => 'CO', 'description' => 'Lifetime benefit maximum has been reached for this service/benefit category'],
    ['code' => '150', 'group_code' => 'CO', 'description' => 'Payer deems the information submitted does not support this level of service'],
    ['code' => '151', 'group_code' => 'CO', 'description' => 'Payment adjusted because the payer deems the information submitted does not support this many/frequency of services'],
    ['code' => '152', 'group_code' => 'CO', 'description' => 'Payer deems the information submitted does not support this length of service'],
    ['code' => '153', 'group_code' => 'CO', 'description' => 'Payer deems the information submitted does not support this dosage'],
    ['code' => '154', 'group_code' => 'CO', 'description' => 'Payer deems the information submitted does not support this day\'s supply'],
    ['code' => '155', 'group_code' => 'CO', 'description' => 'Patient refused the service/procedure'],
    ['code' => '157', 'group_code' => 'CO', 'description' => 'Service/procedure was provided as a result of an act of war'],
    ['code' => '158', 'group_code' => 'CO', 'description' => 'Service/procedure was provided outside of the United States'],
    ['code' => '159', 'group_code' => 'CO', 'description' => 'Service/procedure was provided as a result of terrorism'],
    ['code' => '160', 'group_code' => 'CO', 'description' => 'Injury/illness was the result of an activity that is a benefit exclusion'],
    ['code' => '161', 'group_code' => 'CO', 'description' => 'Provider performance/bonus/penalty adjustment'],
    ['code' => '163', 'group_code' => 'CO', 'description' => 'Attachment/other documentation referenced on the claim was not received'],
    ['code' => '164', 'group_code' => 'CO', 'description' => 'Attachment/other documentation referenced on the claim was not received in a timely fashion'],
    ['code' => '166', 'group_code' => 'CO', 'description' => 'These services were submitted after this payers responsibility for processing claims under this plan ended'],
    ['code' => '167', 'group_code' => 'CO', 'description' => 'This (these) diagnosis(es) is (are) not covered'],
    ['code' => '169', 'group_code' => 'CO', 'description' => 'Alternate benefit has been provided'],
    ['code' => '170', 'group_code' => 'CO', 'description' => 'Payment is denied when performed/billed by this type of provider'],
    ['code' => '171', 'group_code' => 'CO', 'description' => 'Payment is denied when performed/billed by this type of provider in this type of facility'],
    ['code' => '172', 'group_code' => 'CO', 'description' => 'Payment is adjusted when performed/billed by a provider of this specialty'],
    ['code' => '173', 'group_code' => 'CO', 'description' => 'Service/equipment/drug is not covered when performed/billed by this type of provider'],
    ['code' => '174', 'group_code' => 'CO', 'description' => 'Service was not prescribed by a physician'],
    ['code' => '175', 'group_code' => 'CO', 'description' => 'Prescription is incomplete'],
    ['code' => '176', 'group_code' => 'CO', 'description' => 'Prescription is not current'],
    ['code' => '177', 'group_code' => 'CO', 'description' => 'Patient has not met the required eligibility requirements'],
    ['code' => '178', 'group_code' => 'CO', 'description' => 'Patient has not met the required spend down requirements'],
    ['code' => '179', 'group_code' => 'CO', 'description' => 'Patient has not met the required waiting requirements'],
    ['code' => '180', 'group_code' => 'CO', 'description' => 'Patient has not met the required residency requirements'],
    ['code' => '181', 'group_code' => 'CO', 'description' => 'Procedure code was invalid on the date of service'],
    ['code' => '182', 'group_code' => 'CO', 'description' => 'Procedure modifier was invalid on the date of service'],
    ['code' => '183', 'group_code' => 'CO', 'description' => 'The referring provider is not eligible to refer the service billed'],
    ['code' => '184', 'group_code' => 'CO', 'description' => 'The prescribing/ordering provider is not eligible to prescribe/order the service billed'],
    ['code' => '185', 'group_code' => 'CO', 'description' => 'The rendering provider is not eligible to perform the service billed'],
    ['code' => '186', 'group_code' => 'CO', 'description' => 'Level of care change adjustment'],
    ['code' => '187', 'group_code' => 'CO', 'description' => 'Consumer Spending Account payments (includes but is not limited to Health FSA, HRA, HSA)'],
    ['code' => '188', 'group_code' => 'CO', 'description' => 'This product/procedure is only covered when used according to FDA recommendations'],
    ['code' => '189', 'group_code' => 'CO', 'description' => 'Not otherwise classified or unlisted procedure code was billed when there is a specific procedure code for this procedure/service'],
    ['code' => '190', 'group_code' => 'CO', 'description' => 'Payment is included in the allowance for a Skilled Nursing Facility (SNF) qualified stay'],
    ['code' => '192', 'group_code' => 'CO', 'description' => 'Non standard adjustment code from paper remittance'],
    ['code' => '193', 'group_code' => 'CO', 'description' => 'Original payment decision is being maintained. Upon review, it was determined that this claim was processed properly'],
    ['code' => '194', 'group_code' => 'CO', 'description' => 'Anesthesia performed by the operating physician, the assistant surgeon or the attending physician'],
    ['code' => '195', 'group_code' => 'CO', 'description' => 'Refund issued to an erroneous priority payer for this claim/service'],
    ['code' => '197', 'group_code' => 'CO', 'description' => 'Precertification/authorization/notification/pre-treatment absent'],
    ['code' => '198', 'group_code' => 'CO', 'description' => 'Precertification/authorization exceeded'],
    ['code' => '199', 'group_code' => 'CO', 'description' => 'Revenue code and Procedure code do not match'],
    ['code' => '200', 'group_code' => 'CO', 'description' => 'Expenses incurred during lapse in coverage'],
    ['code' => '201', 'group_code' => 'CO', 'description' => 'Patient is responsible for amount of this claim/service through set aside arrangement or other agreement'],
    ['code' => '202', 'group_code' => 'CO', 'description' => 'Non-covered personal comfort or convenience services'],
    ['code' => '203', 'group_code' => 'CO', 'description' => 'Discontinued or reduced service'],
    ['code' => '204', 'group_code' => 'CO', 'description' => 'This service/equipment/drug is not covered under the patient\'s current benefit plan'],
    ['code' => '205', 'group_code' => 'CO', 'description' => 'Pharmacy discount card processing fee'],
    ['code' => '206', 'group_code' => 'CO', 'description' => 'National Provider Identifier - missing'],
    ['code' => '207', 'group_code' => 'CO', 'description' => 'National Provider Identifier - Invalid format'],
    ['code' => '208', 'group_code' => 'CO', 'description' => 'National Provider Identifier - Not matched'],
    ['code' => '209', 'group_code' => 'CO', 'description' => 'Per regulatory or other agreement. The provider cannot collect this amount from the patient'],
    ['code' => '210', 'group_code' => 'CO', 'description' => 'Payment adjusted because pre-certification/authorization not received in a timely fashion'],
    ['code' => '211', 'group_code' => 'CO', 'description' => 'National Drug Codes (NDC) not eligible for rebate, are not covered'],
    ['code' => '212', 'group_code' => 'CO', 'description' => 'Administrative surcharges are not covered'],
    ['code' => '213', 'group_code' => 'CO', 'description' => 'Non-compliance with the physician self referral prohibition legislation or payer policy'],
    ['code' => '214', 'group_code' => 'CO', 'description' => 'Workers\' Compensation claim adjudicated as non-compensable'],
    ['code' => '215', 'group_code' => 'CO', 'description' => 'Based on subrogation of a third party settlement'],
    ['code' => '216', 'group_code' => 'CO', 'description' => 'Based on the findings of a review organization'],
    ['code' => '219', 'group_code' => 'CO', 'description' => 'Based on extent of injury. Adjustment based on the findings of a review organization'],
    ['code' => '222', 'group_code' => 'CO', 'description' => 'Exceeds the contracted maximum number of hours/days/units by this provider for this period'],
    ['code' => '223', 'group_code' => 'CO', 'description' => 'Adjustment code for mandated federal, state or local law/regulation that is not already covered by another code'],
    ['code' => '224', 'group_code' => 'CO', 'description' => 'Patient identification compromised by identity theft. Identity verification required for processing this and future claims'],
    ['code' => '225', 'group_code' => 'CO', 'description' => 'Penalty or Interest Payment by Payer'],
    ['code' => '226', 'group_code' => 'CO', 'description' => 'Information requested from the Billing/Rendering Provider was not provided or not provided timely or was insufficient/incomplete'],
    ['code' => '227', 'group_code' => 'CO', 'description' => 'Information requested from the patient/insured/responsible party was not provided or was insufficient/incomplete'],
    ['code' => '228', 'group_code' => 'CO', 'description' => 'Denied for failure of this provider, another provider or the subscriber to supply requested information'],
    ['code' => '229', 'group_code' => 'CO', 'description' => 'Partial charge amount not considered by Medicare due to the initial claim Type of Bill being 12X'],
    ['code' => '231', 'group_code' => 'CO', 'description' => 'Mutually exclusive procedures cannot be done in the same day/setting'],
    ['code' => '232', 'group_code' => 'CO', 'description' => 'Institutional Transfer Amount'],
    ['code' => '233', 'group_code' => 'CO', 'description' => 'Services/charges related to the treatment of a hospital-acquired condition or preventable medical error'],
    ['code' => '234', 'group_code' => 'CO', 'description' => 'This procedure is not paid separately when the patient is an inpatient'],
    ['code' => '235', 'group_code' => 'CO', 'description' => 'Sales Tax'],
    ['code' => '236', 'group_code' => 'CO', 'description' => 'This procedure or procedure/modifier combination is not compatible with another procedure or procedure/modifier combination already paid'],
    ['code' => '237', 'group_code' => 'CO', 'description' => 'Legislated/Regulatory Penalty. At least one Remark Code must be provided'],
    ['code' => '238 (238-253 omitted for brevity in generator - add key ones)'],
];

// Fix the bad entry and add more codes programmatically
array_pop($carc);
for ($i = 238; $i <= 253; $i++) {
    $carc[] = ['code' => (string) $i, 'group_code' => 'CO', 'description' => 'Standard X12 835 claim adjustment reason code '.$i];
}

$rarc = [
    ['code' => 'MA01', 'description' => 'Alert: If you do not agree with what we approved for these services, you may appeal our decision'],
    ['code' => 'MA02', 'description' => 'Alert: This is a duplicate claim for services previously processed'],
    ['code' => 'MA03', 'description' => 'Alert: This is a split service and represents a portion of the units from the originally submitted service'],
    ['code' => 'MA04', 'description' => 'Alert: This is a split service and represents a portion of the units from the originally submitted service'],
    ['code' => 'MA05', 'description' => 'Alert: This is a split service and represents a portion of the units from the originally submitted service'],
    ['code' => 'MA06', 'description' => 'Alert: This is a split service and represents a portion of the units from the originally submitted service'],
    ['code' => 'MA07', 'description' => 'Alert: The claim information has also been forwarded to Medicaid for review'],
    ['code' => 'MA08', 'description' => 'Alert: Claim information was not forwarded to the patient\'s supplemental insurer because the supplemental insurer does not participate in the Medicare crossover program'],
    ['code' => 'MA09', 'description' => 'Alert: Claim submitted as unassigned but processed as assigned per the patient\'s request for payment to be made directly to the provider'],
    ['code' => 'MA10', 'description' => 'Alert: The patient\'s payment was in excess of the amount owed. You must refund the overpayment to the patient'],
    ['code' => 'MA11', 'description' => 'Alert: Payment for this service is included in the payment for another service that has already been adjudicated'],
    ['code' => 'MA12', 'description' => 'Alert: You have not established that you are the patient\'s representative for purposes of filing an appeal'],
    ['code' => 'MA13', 'description' => 'Alert: You may be subject to penalties if you bill the patient for amounts not reported with this notice'],
    ['code' => 'MA14', 'description' => 'Alert: The patient is a member of an employer-sponsored prepaid health plan. Services are subject to that plan\'s payment rules'],
    ['code' => 'MA15', 'description' => 'Alert: Your claim has been separated to expedite handling. You will receive a separate notice for the other services reported'],
    ['code' => 'MA16', 'description' => 'Alert: The patient is a member of an employer-sponsored prepaid health plan. Services are subject to that plan\'s payment rules'],
    ['code' => 'MA17', 'description' => 'Alert: Payment is based on a reasonable charge because the provider does not accept assignment and the charge exceeds the reasonable charge'],
    ['code' => 'MA18', 'description' => 'Alert: The claim information is also being forwarded to the patient\'s supplemental insurer'],
    ['code' => 'MA19', 'description' => 'Alert: Information was not sent to the Medicaid program because the supplemental insurer does not participate in the Medicare crossover program'],
    ['code' => 'MA20', 'description' => 'Alert: Skilled Nursing Facility (SNF) stay not covered when care is primarily related to the use of an urethral catheter for convenience or the control of incontinence'],
    ['code' => 'MA21', 'description' => 'Alert: Missing/incomplete/invalid information, but claim was processed in accordance with Medicare policy'],
    ['code' => 'MA22', 'description' => 'Alert: Payment adjusted based on the Medicare Physician Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA23', 'description' => 'Alert: Payment adjusted based on the Medicare Ambulatory Surgical Center Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA24', 'description' => 'Alert: Payment adjusted based on the Medicare Clinical Laboratory Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA25', 'description' => 'Alert: Payment adjusted based on the Medicare DMEPOS Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA26', 'description' => 'Alert: Payment adjusted based on the Medicare Part B Drug Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA27', 'description' => 'Alert: Payment adjusted based on the Medicare Part B Drug Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA28', 'description' => 'Alert: Payment adjusted based on the Medicare Part B DrugView Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA29', 'description' => 'Alert: Payment adjusted based on the Medicare Part B InView Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'MA30', 'description' => 'Alert: Payment adjusted based on the Medicare Part B InView Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'N1', 'description' => 'Alert: You may appeal this decision in writing within the required time limits following receipt of this notice'],
    ['code' => 'N2', 'description' => 'Alert: This allowance has been made in accordance with the most appropriate course of treatment provision of your plan'],
    ['code' => 'N3', 'description' => 'Alert: Missing/incomplete/invalid prior insurance carrier EOB'],
    ['code' => 'N4', 'description' => 'Alert: Missing/incomplete/invalid prior insurance carrier EOB'],
    ['code' => 'N5', 'description' => 'Alert: Missing/incomplete/invalid prior insurance carrier EOB'],
    ['code' => 'N6', 'description' => 'Alert: Under FEHB, the approved amount is the lower of the billed amount or the prevailing community rate'],
    ['code' => 'N7', 'description' => 'Alert: Processing of this claim/service has included consideration under Major Medical provisions'],
    ['code' => 'N8', 'description' => 'Alert: Crossover claim denied by previous payer and complete claim data not forwarded. Resubmit this claim to this payer for consideration'],
    ['code' => 'N9', 'description' => 'Alert: Adjustment represents the change in patient responsibility based on the reprocessing of a claim/service'],
    ['code' => 'N10', 'description' => 'Alert: Payment based on the findings of a review organization/professional consult/manual adjudication/medical advisor'],
    ['code' => 'N11', 'description' => 'Alert: Payment based on the findings of a review organization/professional consult/manual adjudication/medical advisor'],
    ['code' => 'N12', 'description' => 'Alert: Payment based on the findings of a review organization/professional consult/manual adjudication/medical advisor'],
    ['code' => 'N13', 'description' => 'Alert: Payment based on the findings of a review organization/professional consult/manual adjudication/medical advisor'],
    ['code' => 'N14', 'description' => 'Alert: Payment based on the findings of a review organization/professional consult/manual adjudication/medical advisor'],
    ['code' => 'N15', 'description' => 'Alert: Services for a newborn must be billed separately and cannot be included on the mother\'s claim'],
    ['code' => 'N16', 'description' => 'Alert: Family member cannot act as the patient\'s representative for purposes of filing an appeal'],
    ['code' => 'N17', 'description' => 'Alert: Payment adjusted based on the Medicare Part B Drug Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'N18', 'description' => 'Alert: Payment adjusted based on the Medicare Part B Drug Fee Schedule for the place of service where the service was rendered'],
    ['code' => 'N19', 'description' => 'Alert: Procedure code incidental to primary procedure'],
    ['code' => 'N20', 'description' => 'Alert: Service not payable with other service rendered on the same date'],
    ['code' => 'N21', 'description' => 'Alert: Alert: Your line item has been separated into multiple lines to expedite processing'],
    ['code' => 'N22', 'description' => 'Alert: This procedure code was added/changed because it more accurately describes the services rendered'],
    ['code' => 'N23', 'description' => 'Alert: Patient liability may be affected due to coordination of benefits with other carriers'],
    ['code' => 'N24', 'description' => 'Alert: Missing/incomplete/invalid Electronic Health Record (EHR) incentive program information'],
    ['code' => 'N25', 'description' => 'Alert: This company has been contracted by your benefit plan to provide administrative claims payment services only'],
    ['code' => 'N26', 'description' => 'Alert: Missing/incomplete/invalid diagnosis information'],
    ['code' => 'N27', 'description' => 'Alert: Missing/incomplete/invalid procedure information'],
    ['code' => 'N28', 'description' => 'Alert: Missing/incomplete/invalid revenue code information'],
    ['code' => 'N29', 'description' => 'Alert: Missing/incomplete/invalid type of bill information'],
    ['code' => 'N30', 'description' => 'Alert: Patient cannot be identified as our insured'],
    ['code' => 'M1', 'description' => 'Alert: X-ray not taken within the past 12 months or near a comparable timeframe'],
    ['code' => 'M2', 'description' => 'Alert: Not paid separately when the patient is an inpatient'],
    ['code' => 'M3', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M4', 'description' => 'Alert: Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M5', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M6', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M7', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M8', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M9', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M10', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M11', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M12', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M13', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M14', 'description' => 'Alert: Equipment is the same or similar to equipment already being used'],
    ['code' => 'M15', 'description' => 'Alert: Separately billed services/tests have been bundled as they are considered components of the same procedure'],
    ['code' => 'M16', 'description' => 'Alert: Redundant services'],
    ['code' => 'M17', 'description' => 'Alert: Payment adjusted because this service was not prescribed by a physician'],
    ['code' => 'M18', 'description' => 'Alert: Payment adjusted because this service was not prescribed by a physician'],
    ['code' => 'M19', 'description' => 'Alert: Missing/incomplete/invalid place of service'],
    ['code' => 'M20', 'description' => 'Alert: Missing/incomplete/invalid HCPCS'],
    ['code' => 'M21', 'description' => 'Alert: Missing/incomplete/invalid ICD-10'],
    ['code' => 'M22', 'description' => 'Alert: Missing/incomplete/invalid modifier'],
    ['code' => 'M23', 'description' => 'Alert: Missing/incomplete/invalid revenue code'],
    ['code' => 'M24', 'description' => 'Alert: Missing/incomplete/invalid type of bill'],
    ['code' => 'M25', 'description' => 'Alert: Payment adjusted because medical necessity not established'],
];

$tob = [
    ['code' => '0111', 'description' => 'Hospital Inpatient (including Medicare Part A)', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient'],
    ['code' => '0112', 'description' => 'Hospital Inpatient - Medicare Part B only', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Part B'],
    ['code' => '0113', 'description' => 'Hospital Inpatient - Medicare Part A only', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Part A'],
    ['code' => '0114', 'description' => 'Hospital Inpatient - Medicare Part A and Part B', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient'],
    ['code' => '0121', 'description' => 'Hospital Inpatient (Part A) - Admit through discharge claim', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Admit-Discharge'],
    ['code' => '0122', 'description' => 'Hospital Inpatient (Part A) - Interim - first claim', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Interim First'],
    ['code' => '0123', 'description' => 'Hospital Inpatient (Part A) - Interim - continuing claim', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Interim Continuing'],
    ['code' => '0124', 'description' => 'Hospital Inpatient (Part A) - Interim - last claim', 'facility_type' => 'Hospital', 'care_type' => 'Inpatient Interim Last'],
    ['code' => '0131', 'description' => 'Hospital Outpatient', 'facility_type' => 'Hospital', 'care_type' => 'Outpatient'],
    ['code' => '0132', 'description' => 'Hospital Outpatient - Medicare Part B only', 'facility_type' => 'Hospital', 'care_type' => 'Outpatient Part B'],
    ['code' => '0141', 'description' => 'Hospital Other (Part B)', 'facility_type' => 'Hospital', 'care_type' => 'Other Part B'],
    ['code' => '0181', 'description' => 'Hospital Swing Bed', 'facility_type' => 'Hospital', 'care_type' => 'Swing Bed'],
    ['code' => '0211', 'description' => 'Skilled Nursing Inpatient (Part A)', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Inpatient'],
    ['code' => '0212', 'description' => 'Skilled Nursing Inpatient (Part B)', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Inpatient Part B'],
    ['code' => '0213', 'description' => 'Skilled Nursing Inpatient (Part A and B)', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Inpatient'],
    ['code' => '0221', 'description' => 'Skilled Nursing Inpatient (Part A) - Admit through discharge', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Inpatient Admit-Discharge'],
    ['code' => '0231', 'description' => 'Skilled Nursing Outpatient', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Outpatient'],
    ['code' => '0281', 'description' => 'Skilled Nursing Swing Bed', 'facility_type' => 'Skilled Nursing Facility', 'care_type' => 'Swing Bed'],
    ['code' => '0311', 'description' => 'Home Health (Part A)', 'facility_type' => 'Home Health Agency', 'care_type' => 'Inpatient/Periodic'],
    ['code' => '0321', 'description' => 'Home Health (Part B)', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient/Periodic'],
    ['code' => '0322', 'description' => 'Home Health (Part B) - Interim first claim', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient Interim First'],
    ['code' => '0323', 'description' => 'Home Health (Part B) - Interim continuing claim', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient Interim Continuing'],
    ['code' => '0324', 'description' => 'Home Health (Part B) - Interim last claim', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient Interim Last'],
    ['code' => '0327', 'description' => 'Home Health (Part B) - Replacement of prior claim', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient Replacement'],
    ['code' => '0328', 'description' => 'Home Health (Part B) - Void/cancel prior claim', 'facility_type' => 'Home Health Agency', 'care_type' => 'Outpatient Void'],
    ['code' => '0411', 'description' => 'Religious Nonmedical Health Care Inpatient', 'facility_type' => 'Religious Nonmedical', 'care_type' => 'Inpatient'],
    ['code' => '0711', 'description' => 'Clinic Rural Health', 'facility_type' => 'Clinic', 'care_type' => 'Rural Health'],
    ['code' => '0713', 'description' => 'Clinic Rural Health - Medicare Part B only', 'facility_type' => 'Clinic', 'care_type' => 'Rural Health Part B'],
    ['code' => '0721', 'description' => 'Clinic Hospital Based or Independent Renal Dialysis Center', 'facility_type' => 'Clinic', 'care_type' => 'Dialysis'],
    ['code' => '0731', 'description' => 'Clinic Freestanding', 'facility_type' => 'Clinic', 'care_type' => 'Freestanding'],
    ['code' => '0741', 'description' => 'Clinic Outpatient Rehabilitation Facility (ORF)', 'facility_type' => 'Clinic', 'care_type' => 'ORF'],
    ['code' => '0751', 'description' => 'Clinic Comprehensive Outpatient Rehabilitation Facility (CORF)', 'facility_type' => 'Clinic', 'care_type' => 'CORF'],
    ['code' => '0761', 'description' => 'Clinic Community Mental Health Center', 'facility_type' => 'Clinic', 'care_type' => 'CMHC'],
    ['code' => '0811', 'description' => 'Special Facility Hospice (Nonhospital based)', 'facility_type' => 'Hospice', 'care_type' => 'Nonhospital'],
    ['code' => '0821', 'description' => 'Special Facility Hospice (Hospital based)', 'facility_type' => 'Hospice', 'care_type' => 'Hospital based'],
    ['code' => '0831', 'description' => 'Special Facility Ambulatory Surgery Center', 'facility_type' => 'ASC', 'care_type' => 'Outpatient Surgery'],
    ['code' => '0841', 'description' => 'Special Facility Free Standing Birthing Center', 'facility_type' => 'Birthing Center', 'care_type' => 'Outpatient'],
    ['code' => '0851', 'description' => 'Special Facility Critical Access Hospital', 'facility_type' => 'Critical Access Hospital', 'care_type' => 'Inpatient/Outpatient'],
    ['code' => '0861', 'description' => 'Special Facility Residential Facility', 'facility_type' => 'Residential Facility', 'care_type' => 'Residential'],
    ['code' => '1311', 'description' => 'Hospital Outpatient - Laboratory services provided to non-patients', 'facility_type' => 'Hospital', 'care_type' => 'Outpatient Lab Non-patient'],
    ['code' => '8511', 'description' => 'Critical Access Hospital (CAH) - Admit through discharge', 'facility_type' => 'Critical Access Hospital', 'care_type' => 'Inpatient Admit-Discharge'],
    ['code' => '8512', 'description' => 'Critical Access Hospital (CAH) - Interim first claim', 'facility_type' => 'Critical Access Hospital', 'care_type' => 'Inpatient Interim First'],
    ['code' => '8513', 'description' => 'Critical Access Hospital (CAH) - Interim continuing claim', 'facility_type' => 'Critical Access Hospital', 'care_type' => 'Inpatient Interim Continuing'],
    ['code' => '8514', 'description' => 'Critical Access Hospital (CAH) - Interim last claim', 'facility_type' => 'Critical Access Hospital', 'care_type' => 'Inpatient Interim Last'],
];

$revenue = [
    ['code' => '0022', 'description' => 'Intensive Care Unit', 'category' => 'Room and Board'],
    ['code' => '0023', 'description' => 'Coronary Care Unit', 'category' => 'Room and Board'],
    ['code' => '0024', 'description' => 'Medical/Surgical/GyN', 'category' => 'Room and Board'],
    ['code' => '0110', 'description' => 'Private Room - General Classification', 'category' => 'Room and Board'],
    ['code' => '0120', 'description' => 'Semi-Private Room - General Classification', 'category' => 'Room and Board'],
    ['code' => '0121', 'description' => 'Semi-Private Room - Medical/Surgical/GyN', 'category' => 'Room and Board'],
    ['code' => '0122', 'description' => 'Semi-Private Room - Obstetrics', 'category' => 'Room and Board'],
    ['code' => '0123', 'description' => 'Semi-Private Room - Pediatric', 'category' => 'Room and Board'],
    ['code' => '0124', 'description' => 'Semi-Private Room - Psychiatric', 'category' => 'Room and Board'],
    ['code' => '0125', 'description' => 'Semi-Private Room - Hospice', 'category' => 'Room and Board'],
    ['code' => '0126', 'description' => 'Semi-Private Room - Detoxification', 'category' => 'Room and Board'],
    ['code' => '0127', 'description' => 'Semi-Private Room - Oncology', 'category' => 'Room and Board'],
    ['code' => '0128', 'description' => 'Semi-Private Room - Rehabilitation', 'category' => 'Room and Board'],
    ['code' => '0130', 'description' => 'Private Room - General Classification', 'category' => 'Room and Board'],
    ['code' => '0140', 'description' => 'Private Room - General Classification', 'category' => 'Room and Board'],
    ['code' => '0150', 'description' => 'Ward Room - General Classification', 'category' => 'Room and Board'],
    ['code' => '0160', 'description' => 'Other Room and Board', 'category' => 'Room and Board'],
    ['code' => '0170', 'description' => 'Nursery - General Classification', 'category' => 'Room and Board'],
    ['code' => '0180', 'description' => 'Leave of Absence - General Classification', 'category' => 'Room and Board'],
    ['code' => '0190', 'description' => 'Subacute Care - General Classification', 'category' => 'Room and Board'],
    ['code' => '0200', 'description' => 'Intensive Care Unit - General Classification', 'category' => 'Room and Board'],
    ['code' => '0210', 'description' => 'Coronary Care Unit - General Classification', 'category' => 'Room and Board'],
    ['code' => '0220', 'description' => 'Surgical ICU - General Classification', 'category' => 'Room and Board'],
    ['code' => '0230', 'description' => 'Other ICU - General Classification', 'category' => 'Room and Board'],
    ['code' => '0250', 'description' => 'Pharmacy - General Classification', 'category' => 'Pharmacy'],
    ['code' => '0251', 'description' => 'Pharmacy - Generic Drugs', 'category' => 'Pharmacy'],
    ['code' => '0252', 'description' => 'Pharmacy - Non-Generic Drugs', 'category' => 'Pharmacy'],
    ['code' => '0253', 'description' => 'Pharmacy - Take Home Drugs', 'category' => 'Pharmacy'],
    ['code' => '0254', 'description' => 'Pharmacy - Drugs Incident to Diagnostic or Therapeutic Radiology', 'category' => 'Pharmacy'],
    ['code' => '0255', 'description' => 'Pharmacy - Drugs requiring detailed coding', 'category' => 'Pharmacy'],
    ['code' => '0260', 'description' => 'IV Therapy - General Classification', 'category' => 'IV Therapy'],
    ['code' => '0270', 'description' => 'Medical/Surgical Supplies - General Classification', 'category' => 'Supplies'],
    ['code' => '0271', 'description' => 'Medical/Surgical Supplies - Non-Sterile Supply', 'category' => 'Supplies'],
    ['code' => '0272', 'description' => 'Medical/Surgical Supplies - Sterile Supply', 'category' => 'Supplies'],
    ['code' => '0274', 'description' => 'Medical/Surgical Supplies - Prosthetic/Orthotic Devices', 'category' => 'Supplies'],
    ['code' => '0275', 'description' => 'Medical/Surgical Supplies - Pacemaker', 'category' => 'Supplies'],
    ['code' => '0276', 'description' => 'Medical/Surgical Supplies - Other Implants', 'category' => 'Supplies'],
    ['code' => '0280', 'description' => 'Oncology - General Classification', 'category' => 'Oncology'],
    ['code' => '0290', 'description' => 'Durable Medical Equipment (Other than Renal) - General Classification', 'category' => 'DME'],
    ['code' => '0300', 'description' => 'Laboratory - General Classification', 'category' => 'Laboratory'],
    ['code' => '0301', 'description' => 'Laboratory - Chemistry', 'category' => 'Laboratory'],
    ['code' => '0302', 'description' => 'Laboratory - Immunology', 'category' => 'Laboratory'],
    ['code' => '0305', 'description' => 'Laboratory - Hematology', 'category' => 'Laboratory'],
    ['code' => '0306', 'description' => 'Laboratory - Bacteriology & Microbiology', 'category' => 'Laboratory'],
    ['code' => '0307', 'description' => 'Laboratory - Urology', 'category' => 'Laboratory'],
    ['code' => '0310', 'description' => 'Laboratory - Pathology', 'category' => 'Laboratory'],
    ['code' => '0311', 'description' => 'Laboratory - Cytology', 'category' => 'Laboratory'],
    ['code' => '0312', 'description' => 'Laboratory - Histology', 'category' => 'Laboratory'],
    ['code' => '0320', 'description' => 'Radiology - Diagnostic - General Classification', 'category' => 'Radiology'],
    ['code' => '0321', 'description' => 'Radiology - Diagnostic - Angiocardiography', 'category' => 'Radiology'],
    ['code' => '0322', 'description' => 'Radiology - Diagnostic - Arthrography', 'category' => 'Radiology'],
    ['code' => '0323', 'description' => 'Radiology - Diagnostic - Arteriography', 'category' => 'Radiology'],
    ['code' => '0324', 'description' => 'Radiology - Diagnostic - Chest X-Ray', 'category' => 'Radiology'],
    ['code' => '0330', 'description' => 'Radiology - Therapeutic and/or Chemotherapy Administration', 'category' => 'Radiology'],
    ['code' => '0340', 'description' => 'Nuclear Medicine - General Classification', 'category' => 'Nuclear Medicine'],
    ['code' => '0350', 'description' => 'CT Scan - General Classification', 'category' => 'Radiology'],
    ['code' => '0351', 'description' => 'CT Scan - Head Scan', 'category' => 'Radiology'],
    ['code' => '0352', 'description' => 'CT Scan - Body Scan', 'category' => 'Radiology'],
    ['code' => '0360', 'description' => 'Operating Room Services - General Classification', 'category' => 'Operating Room'],
    ['code' => '0370', 'description' => 'Anesthesia - General Classification', 'category' => 'Anesthesia'],
    ['code' => '0380', 'description' => 'Blood - General Classification', 'category' => 'Blood'],
    ['code' => '0390', 'description' => 'Blood Storage and Processing - General Classification', 'category' => 'Blood'],
    ['code' => '0400', 'description' => 'Other Imaging Services - General Classification', 'category' => 'Imaging'],
    ['code' => '0410', 'description' => 'Respiratory Services - General Classification', 'category' => 'Respiratory'],
    ['code' => '0420', 'description' => 'Physical Therapy - General Classification', 'category' => 'Therapy'],
    ['code' => '0430', 'description' => 'Occupational Therapy - General Classification', 'category' => 'Therapy'],
    ['code' => '0440', 'description' => 'Speech-Language Pathology - General Classification', 'category' => 'Therapy'],
    ['code' => '0450', 'description' => 'Emergency Room - General Classification', 'category' => 'Emergency'],
    ['code' => '0451', 'description' => 'Emergency Room - EM Triage/Fee', 'category' => 'Emergency'],
    ['code' => '0452', 'description' => 'Emergency Room - EM Visit', 'category' => 'Emergency'],
    ['code' => '0456', 'description' => 'Emergency Room - Urgent Care', 'category' => 'Emergency'],
    ['code' => '0460', 'description' => 'Pulmonary Function - General Classification', 'category' => 'Respiratory'],
    ['code' => '0470', 'description' => 'Audiology - General Classification', 'category' => 'Therapy'],
    ['code' => '0480', 'description' => 'Cardiology - General Classification', 'category' => 'Cardiology'],
    ['code' => '0481', 'description' => 'Cardiology - Cardiac Cath Lab', 'category' => 'Cardiology'],
    ['code' => '0482', 'description' => 'Cardiology - Stress Test', 'category' => 'Cardiology'],
    ['code' => '0483', 'description' => 'Cardiology - Echocardiology', 'category' => 'Cardiology'],
    ['code' => '0490', 'description' => 'Ambulatory Surgical Care - General Classification', 'category' => 'Surgery'],
    ['code' => '0500', 'description' => 'Outpatient Services - General Classification', 'category' => 'Outpatient'],
    ['code' => '0510', 'description' => 'Clinic - General Classification', 'category' => 'Clinic'],
    ['code' => '0520', 'description' => 'Freestanding Clinic - General Classification', 'category' => 'Clinic'],
    ['code' => '0530', 'description' => 'Osteopathic Services - General Classification', 'category' => 'Osteopathic'],
    ['code' => '0540', 'description' => 'Ambulance - General Classification', 'category' => 'Ambulance'],
    ['code' => '0550', 'description' => 'Skilled Nursing - General Classification', 'category' => 'Skilled Nursing'],
    ['code' => '0560', 'description' => 'Home Health - General Classification', 'category' => 'Home Health'],
    ['code' => '0570', 'description' => 'Hospice - General Classification', 'category' => 'Hospice'],
    ['code' => '0580', 'description' => 'Respite Care - General Classification', 'category' => 'Respite'],
    ['code' => '0590', 'description' => 'Reserved', 'category' => 'Other'],
    ['code' => '0600', 'description' => 'Radiation Therapy - General Classification', 'category' => 'Radiation Therapy'],
    ['code' => '0610', 'description' => 'Magnetic Resonance Technology (MRT) - General Classification', 'category' => 'Imaging'],
    ['code' => '0621', 'description' => 'Medical/Surgical Supplies - General Classification', 'category' => 'Supplies'],
    ['code' => '0630', 'description' => 'Pharmacy - Extension of 025X - General Classification', 'category' => 'Pharmacy'],
    ['code' => '0640', 'description' => 'Home IV Therapy Services - General Classification', 'category' => 'Home Health'],
    ['code' => '0650', 'description' => 'Hospice Service - General Classification', 'category' => 'Hospice'],
    ['code' => '0660', 'description' => 'Respite Care - General Classification', 'category' => 'Respite'],
    ['code' => '0710', 'description' => 'Recovery Room - General Classification', 'category' => 'Operating Room'],
    ['code' => '0720', 'description' => 'Labor Room/Delivery - General Classification', 'category' => 'Labor and Delivery'],
    ['code' => '0730', 'description' => 'EKG/ECG - General Classification', 'category' => 'Cardiology'],
    ['code' => '0740', 'description' => 'EEG - General Classification', 'category' => 'Neurology'],
    ['code' => '0750', 'description' => 'Gastro-Intestinal Services - General Classification', 'category' => 'GI'],
    ['code' => '0760', 'description' => 'Specialty Services - General Classification', 'category' => 'Specialty'],
    ['code' => '0770', 'description' => 'Preventive Services - General Classification', 'category' => 'Preventive'],
    ['code' => '0780', 'description' => 'Telemedicine - General Classification', 'category' => 'Telemedicine'],
    ['code' => '0790', 'description' => 'Extra-Corporeal Shock Wave Therapy (ESWT) - General Classification', 'category' => 'Therapy'],
    ['code' => '0800', 'description' => 'Inpatient Renal Dialysis - General Classification', 'category' => 'Dialysis'],
    ['code' => '0810', 'description' => 'Acquisition of Body Components - General Classification', 'category' => 'Organ Acquisition'],
    ['code' => '0900', 'description' => 'Psychiatric/Psychological Services - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '0910', 'description' => 'Psychiatric/Psychological Services - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '0920', 'description' => 'Other Diagnostic Services - General Classification', 'category' => 'Diagnostic'],
    ['code' => '0930', 'description' => 'Medical Rehabilitation Day Program - General Classification', 'category' => 'Rehabilitation'],
    ['code' => '0940', 'description' => 'Other Therapeutic Services - General Classification', 'category' => 'Therapy'],
    ['code' => '0950', 'description' => 'Other Outpatient Services - General Classification', 'category' => 'Outpatient'],
    ['code' => '0960', 'description' => 'Professional Fees - General Classification', 'category' => 'Professional Fees'],
    ['code' => '0970', 'description' => 'Professional Fees - General Classification', 'category' => 'Professional Fees'],
    ['code' => '0980', 'description' => 'Professional Fees - General Classification', 'category' => 'Professional Fees'],
    ['code' => '0990', 'description' => 'Professional Fees - General Classification', 'category' => 'Professional Fees'],
    ['code' => '1000', 'description' => 'Behavioral Health Accommodations - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '1001', 'description' => 'Behavioral Health Residential Treatment - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '1002', 'description' => 'Behavioral Health Partial Hospitalization - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '1003', 'description' => 'Behavioral Health Intensive Outpatient - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '1004', 'description' => 'Behavioral Health Community Residential - General Classification', 'category' => 'Behavioral Health'],
    ['code' => '1005', 'description' => 'Behavioral Health Substance Abuse - General Classification', 'category' => 'Behavioral Health'],
];

foreach ([
    'modifiers.json' => $modifiers,
    'carc.json' => $carc,
    'rarc.json' => $rarc,
    'type-of-bill.json' => $tob,
    'revenue-codes.json' => $revenue,
] as $file => $data) {
    file_put_contents($dir.'/'.$file, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));
    echo $file.': '.count($data).PHP_EOL;
}
